@startuml

object ProgrammingParadigms

object Imperative
object Declarative

object Procedural

Procedural : exampleLang = "fortran"

object ObjectOriented

ObjectOriented : exampleLang = "java"

object Structured

Structured : exampleLang = "algol"

object Logic

Logic : exampleLang = "prolog"

object Functional

Functional : exampleLang = "haskel"

object DataDriven

DataDriven : exampleLang = "perl"

Imperative <|-- ProgrammingParadigms
Declarative <|-- ProgrammingParadigms

Procedural <|-- Imperative
ObjectOriented <|-- Imperative
Structured <|-- Imperative

Logic <|-- Declarative
Functional <|-- Declarative
DataDriven <|-- Declarative

@enduml